[32mINFO    [0m integration.helpers:helpers.py:367 Calling: PUT -- https://10.21.247.19:9200/test_index
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: PUT -- https://10.21.247.19:9200/test_index/_doc/12
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: POST -- https://10.21.247.19:9200/test_index/_refresh
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.21.247.150:9200/test_index/_search?preference=_only_local
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.21.247.19:9200/test_index/_search?preference=_only_local
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.21.247.73:9200/test_index/_search?preference=_only_local
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: DELETE -- https://10.21.247.19:9200/test_index/
[32mINFO    [0m integration.ha.helpers:helpers.py:247 Continuous writes result: namespace(max_stored_id=121, count=122, last_expected_id=121)
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.21.247.19:9200/series_index/_search_shards
[32mINFO    [0m integration.ha.conftest:conftest.py:39 



The writes have been cleared.