[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.156.50.146:9200/_cluster/state/cluster_manager_node
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.156.50.146:9200/_nodes
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.156.50.146:9200/
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.156.50.146:9200/
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.156.50.146:9200/
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.156.50.53:9200/
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.156.50.146:9200/
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.156.50.246:9200/
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.156.50.53:9200/_cluster/state/cluster_manager_node
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.156.50.53:9200/_nodes
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.156.50.146:9200/
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.156.50.146:9200/_nodes
[32mINFO    [0m integration.ha.helpers:helpers.py:247 Continuous writes result: namespace(max_stored_id=222, count=223, last_expected_id=222)
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.156.50.146:9200/series_index/_search_shards
[32mINFO    [0m integration.ha.conftest:conftest.py:57 



The writes have been cleared.