[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.180.17.192:9200/
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.180.17.136:9200/
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.180.17.92:9200/
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.180.17.136:9200/_nodes
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.180.17.136:9200/_cluster/health
[32mINFO    [0m integration.ha.helpers:helpers.py:247 Continuous writes result: namespace(max_stored_id=176, count=177, last_expected_id=176)
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.180.17.136:9200/series_index/_search_shards
[32mINFO    [0m integration.ha.conftest:conftest.py:57 



The writes have been cleared.