[32mINFO    [0m integration.ha.test_backups:test_backups.py:440 Syncing credentials for aws
[32mINFO    [0m juju.model:model.py:2958 Waiting for model:
  main/0 [executing] maintenance: Backup setup started.
  s3-integrator/0 [executing] active: 
[32mINFO    [0m juju.model:model.py:2958 Waiting for model:
  main/0 [executing] maintenance: Configuring backup service...
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.114.28.52:9200/_recovery?human
[32mINFO    [0m integration.ha.helpers:helpers.py:247 Continuous writes result: namespace(max_stored_id=199, count=200, last_expected_id=199)
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.114.28.52:9200/series_index/_search_shards
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: POST -- https://10.114.28.52:9200/series_index/_refresh
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.114.28.52:9200/series_index/_count
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.114.28.52:9200/_recovery?human
[32mINFO    [0m integration.ha.conftest:conftest.py:39 



The writes have been cleared.